SELECT
    ACCOUNT_ID,
    CUSTOMER_ID,
    TRIM(ORIGINAL_CREDITOR) AS ORIGINAL_CREDITOR,
    BALANCE,
    UPPER(TRIM(ACCOUNT_STATUS)) AS ACCOUNT_STATUS,
    ACCOUNT_OPEN_DATE
FROM {{ source('raw', 'accounts') }}
