SELECT
    CASE_ID,
    ACCOUNT_ID,
    UPPER(TRIM(CASE_TYPE)) AS CASE_TYPE,
    UPPER(TRIM(CASE_STATUS)) AS CASE_STATUS,
    UPPER(TRIM(COURT_STATE)) AS COURT_STATE,
    FILING_DATE
FROM {{ source('raw', 'legal_cases') }}
